// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TypeSpec")>]
[<assembly: AssemblyProductAttribute("TypeSpec")>]
[<assembly: AssemblyDescriptionAttribute("Versionable Type Contracts")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TypeSpec"
    let [<Literal>] AssemblyProduct = "TypeSpec"
    let [<Literal>] AssemblyDescription = "Versionable Type Contracts"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
